services:
  ragknowledgebasefrontend:
    image: ragknowledgebasefrontend
    build:
      context: RAG-optimized/frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
